### ISSUE TITLE
proctl_test.go:23: Launch(): could not fork/exec

### ISSUE THREAD

**Issue by laher** [derekparker/delve#134]
Running `make test` on a mac, I get the above error.
Subsequently, when I try `make install`, it installs without complaint, but when `dlv run`, it doesn't allow any subcommands (`Command failed: debugger isn't running`)

See output from `make test`, below (note that I sprintf'd the return value of C.fork_exec incase it helps. It returns '-1').

Please let me know if you need any more info. Ta.

➜  delve git:(master) ✗ sw_vers -productVersion 
10.10.2
➜  delve git:(master) ✗ CERT=dlv-cert make test
go test github.com/derekparker/delve/terminal github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/source github.com/derekparker/delve/dwarf/line
ok      github.com/derekparker/delve/terminal   0.028s
ok      github.com/derekparker/delve/dwarf/frame        0.006s
ok      github.com/derekparker/delve/dwarf/op   0.005s
ok      github.com/derekparker/delve/dwarf/util 0.006s
ok      github.com/derekparker/delve/source     0.007s
ok      github.com/derekparker/delve/dwarf/line 0.173s
cd proctl && go test -c github.com/derekparker/delve/proctl && codesign -s dlv-cert ./proctl.test && ./proctl.test  && rm ./proctl.test
--- FAIL: TestExit (0.15s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestHalt (0.16s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestStep (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestBreakPoint (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestBreakPointInSeperateGoRoutine (0.16s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestBreakPointWithNonExistantFunction (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestClearBreakPoint (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestNextGeneral (0.16s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestNextGoroutine (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestNextFunctionReturn (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestNextFunctionReturnDefer (0.16s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestRuntimeBreakpoint (0.16s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestFindReturnAddress (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestSwitchThread (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestFunctionCall (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestVariableEvaluation (0.17s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestVariableFunctionScoping (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
--- FAIL: TestLocalVariables (0.00s)
        proctl_test.go:23: Launch(): could not fork/exec -1
FAIL
make: *** [test] Error 1

**Comment by derekparker** [comment]
You have to provide an environment variable that specifies the cert to sign the program with. Delve must be codesigned on OSX, even some of the test binaries.

I will update the makefile to give a more meaningful error if that env var isn't there, however have you taken the steps to create a self signed cert? The steps are outlined in the README.

**Comment by laher** [comment]
Yes I did that - you can see in the shell output `CERT=dlv-cert make test`.
Sorry, I  didn't clarify it in the initial description.
So, yes I created the self-signed certificate, and also added the exception
which permits codesign to use the cert without asking for authentication.
Thanks for the speedy response, and BTW delve is awesome (I've been using
it on Linux a little bit already)

**Comment by derekparker** [comment]
Ah, should have looked a little closer! Sorry about that.

A few questions:
- Were you able to test/compile Delve correctly before using this cert?
- What version are you running? (git SHA is fine)

Thanks, I really appreciate that!

**Comment by laher** [comment]
Hi, no those test cases for the proctl package are failing, with or without the cert - same errors. But I could run go test on all the other packages. Note, when run as root, `go test` (in proctl) and `CERT=dlv-cert make test` both work OK. So, I guess its a permissions problem.

I did some printf-ing to get more info from the C code, which led me towards the `task_for_pid` call in proctl_darwin.c, which is returning 5 instead of 0. I'm totally out of my depth with the mach stuff - I'm hoping it means more to you than it does to me.

Cheers

**Comment by laher** [comment]
My delve version:
bash-3.2$ git log -1
commit 7cb6480142a727faa5378cc098e8b64d48a336c6
Author: Derek Parker <parkerderek86@gmail.com>
Date:   Fri May 15 15:32:47 2015 -0500

**Comment by derekparker** [comment]
@laher sorry for the delay in getting back to you. So, to clarify, were you able to use that same cert to successfully run the tests previously? If that cert never worked before, it could just be an issue with the CERT that was created.

**Comment by laher** [comment]
No I haven't been able to run the tests with the cert, so you're probably right. I'll try re-creating a cert and do some more diagnostics on it if I run into problems. I'll let you know once I get a chance to look into it. Ta

**Comment by derekparker** [comment]
Sounds good, if you happen to fix the issue by regenerating a cert just close this issue out.

**Comment by leepa** [comment]
I need to +1 here and say I have the same problem. Followed the guide and the cert exists in my system keychain.

```
commit c692f620055782d7be2405ad8af937cfb8ee59a4
Author: Derek Parker <parkerderek86@gmail.com>
Date:   Tue Jun 2 08:26:35 2015 -0500
```

```
$ sw_vers -productVersion
10.10.3
```

```
cd proctl && go test -c github.com/derekparker/delve/proctl && codesign -s dlv-cert ./proctl.test && ./proctl.test  && rm ./proctl.test
--- FAIL: TestExit (0.25s)
	proctl_test.go:23: Launch(): could not fork/exec
--- FAIL: TestHalt (0.24s)
	proctl_test.go:23: Launch(): could not fork/exec
...
etc.
```

**Comment by leepa** [comment]
Worth adding the signing is present on my main dlv command similar issue with 'debugger isn't running'

```
➜  delve git:(master) codesign -d ~/gopath/bin/dlv -vvvv
Executable=/Users/leepa/gopath/bin/dlv
Identifier=org.dlv
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=35776 flags=0x0(none) hashes=1784+2 location=embedded
Hash type=sha1 size=20
CDHash=96ba97f10598163487827ddafe7a6cdadb4f51e6
Signature size=1232
Authority=dlv-cert
Signed Time=10 Jun 2015 15:19:38
Info.plist entries=4
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=2 size=248
```

**Comment by laher** [comment]
Last week I tried some new certs and got no further.

But today I just `git pull`ed, and seem to have got a bit further. 
It seems to sort-of attach now, but the only thing that sorta works is 'continue' (if I invoke continue as the first command), and it can't seem to find the source.

So, here it is on a basic "Hello world!" app:

dlv run
Type 'help' for list of commands.
(dlv) continue
Hello world!Stopped at: 0x0
=>    no source available

When I run various other commands, I get the following:

dlv run
Type 'help' for list of commands.
(dlv) step
Stopped at: 0x7fff6d2c6001
=>    no source available
(dlv) goroutines
[0 goroutines]
(dlv) threads
* Thread 10499 at :0
(dlv) info args
Command failed: unable to find function context
(dlv) info locals
Command failed: unable to find function context
(dlv) next
Command failed: error derefing defer could not read memory
(dlv) continue
Command failed: could not get registers: could not get registers

... `info sources` and `info funcs` give very long outputs, but seem to be working OK
Cheers

**Comment by derekparker** [comment]
@laher are you able to run the tests now? Can you point me to the source code of the program you're trying to debug in the last example?

**Comment by laher** [comment]
Yes, I can run the tests now. BUT, only if I `cd` into the proc folder and run the sequence of commands directly (cd proc && go test -c ... && codesign ... && ./proc.test ...). Otherwise it fails with an import path error. I think that problem is a weird idiosyncrasy of `go test -c`, which also happens on Linux if I use `go test -c` on the proc package. I can create another ticket for that with details, because I *think* it's a new problem. 

Here's my 'Hello world' (I previously tried more substantial programs - same result):

```
package main

import "fmt"

func main() {
	fmt.Printf("Hello world!")
}
```

**Comment by derekparker** [comment]
@laher definitely make a ticket about that `make` path issue, I have made some changes to the Makefile which could be causing that issue.

**Comment by laher** [comment]
Hey! You fixed that path issue. I was just making a pull request, and then I realised it was already fixed. Sweet as.

**Comment by intel352** [comment]
I had the same issue, until I killed taskgated as per the instructions:
```bash
$ ps -ax | grep taskgated
$ sudo kill 107  #the process ID that printed for me from the above grep
```

I then re-ran the tests, and re-built Delve, everything proceeded fine from this point forward.

**Comment by derekparker** [comment]
Going to close this issue as it should be solved. Please reopen if not.

**Comment by debedb** [comment]
I cannot reopen, I think, as I am not the original submitter, but I am having the same issue as well. Tried the above steps in various combinations (killing taskgated, created several certificates, etc): still the "could not fork/exec" issue persists.

**Comment by venjiang** [comment]
How should I do?

**Comment by orsonwang** [comment]
In my case, in addition to "Allow all access" at private key. 
<img width="526" alt="screen shot 2016-02-23 at 20 57 45" src="https://cloud.githubusercontent.com/assets/422107/13252267/bd4926aa-da70-11e5-9210-99b503218387.png">
I have to set "Alway Trust" at certificate. 
<img width="758" alt="screen shot 2016-02-23 at 20 58 48" src="https://cloud.githubusercontent.com/assets/422107/13252280/d6dffe22-da70-11e5-9b80-28d150c5aa59.png">

Then it finally works.

**Comment by laher** [comment]
I should note that delve now works for me on my mac, since about 2 months
ago.
I did nothing except to get-latest, and rebuild. ¯\_(ツ)_/¯

**Comment by orsonwang** [comment]
That's good. it's only the record of I trying to figure out how to making it work on my OSX 10.11.4 Beta and golang 1.6.

**Comment by gertcuykens** [comment]
```
go version go1.6.2 darwin/amd64
Delve Debugger
Version: 0.11.0-alpha
Build: 8b4abf59987ccc15040c70b1251ace0515c0397c
OSX 10.11.5
```

Only `sudo dlv debug` works for me without `sudo` I get
`could not launch process: could not fork/exec`

Also it's not clear how you can test the certificate.

```
package main
import "C"
func main() {
    println("hello")
}
```
Assuming if this works without sudo, all certificate steps are done correctly and it's not the certificate or the permissions of the certificate?
```
go build -ldflags -s main.go
go build main.go
codesign -s delve-cert main
./main
hello
```

**Comment by aarzilli** [comment]
@gertcuykens: try installing with homebrew (either the permissions on the certificate are wrong or taskgated wasn't restarted): https://github.com/go-delve/homebrew-delve

**Comment by gertcuykens** [comment]
I will try that and it probably will work but aside from that in my above question, what is the reason I can use the same certificate in the same state as dlv was signed in and make a hello world app run without sudo? There must be yet another permission setting not mentioned in this thread. For me it's important that we understand all aspects of this. Not just homebrew magic :) So basicly I want a test case other then dlv itself that gives me the exact same error message `could not launch process: could not fork/exec` running a hello world example. Thank you :)

**Comment by aarzilli** [comment]
There is no other setting, you either missed one step or did not restart taskgated. Your helloworld example does not test the certificate because it doesn't do anything that requires a certificate.

**Comment by gertcuykens** [comment]
Ok make sense thank you, can you maybe add a few lines to the hello world example that would use the certificate and generate the same error? I really want to understand what is going on, and from there figure out if we could make better error messages. Just need the basics then I will direct my questions to stackoverflow to dissect more into this.

**Comment by aarzilli** [comment]
Take a look at `proc.Launch` in proc/proc_darwin.go and also `fork_exec` in proc/exec_darwin.c, that's where the message comes from. You should also check out the branch at #525 since some of this code is about to change.

You could also look at [this](http://opensource.apple.com//source/xnu/xnu-2422.1.72/tools/tests/unit_tests/ptrace_tests_10767133_src/ptrace_tests_10767133.c)

**Comment by gertcuykens** [comment]
`brew install go-delve/delve/delve --HEAD`

Worked, but I notice that the new key has different permission than documented

generated brew key
![image](https://cloud.githubusercontent.com/assets/863731/15411221/d16d813e-1e1e-11e6-9be1-f34817b4a92f.png)

my key
![image](https://cloud.githubusercontent.com/assets/863731/15411237/de9f9720-1e1e-11e6-917b-38e3397b587d.png)

Everything else is the same, can it be confirmed please by others that you need more permissions than documented?

**Comment by aarzilli** [comment]
@gertcuykens: if you `make test` using your key does it work now?

**Comment by gertcuykens** [comment]
Both certificates seem to be working now, indicating the restart taskgated was not successful the first time but still I am convinced it was restarted the first time for sure. So the question now would be can you make the brew certificate only Trust Code Signing? 

```
make test
go test -exec=/Users/gert/go/src/github.com/derekparker/delve/scripts/testsign -ldflags="-s -X main.Build=8b4abf59987ccc15040c70b1251ace0515c0397c" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/cmd/dlv/cmds github.com/derekparker/delve/config github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/line github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/reader github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/proc github.com/derekparker/delve/proc/test github.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc1 github.com/derekparker/delve/service/rpc2 github.com/derekparker/delve/service/test github.com/derekparker/delve/service/test/cmd github.com/derekparker/delve/terminal github.com/derekparker/delve/version
?   	github.com/derekparker/delve/cmd/dlv	[no test files]
?   	github.com/derekparker/delve/cmd/dlv/cmds	[no test files]
?   	github.com/derekparker/delve/config	[no test files]
ok  	github.com/derekparker/delve/dwarf/frame	0.170s
ok  	github.com/derekparker/delve/dwarf/line	0.415s
ok  	github.com/derekparker/delve/dwarf/op	0.180s
?   	github.com/derekparker/delve/dwarf/reader	[no test files]
ok  	github.com/derekparker/delve/dwarf/util	0.163s
Hello, World!
Hello, World!
past main
foo
--- FAIL: TestNextConcurrent (0.40s)
	proc_test.go:80: failed assertion at proc_test.go:415: EvalVariable - could not read memory
--- FAIL: TestNextConcurrentVariant2 (0.10s)
	proc_test.go:80: failed assertion at proc_test.go:452: EvalVariable - could not read memory
foo
Hello, World!
bye
hi
hi
hi
hi
Fri May 20 13:09:15 CEST 2016
default
id: 1 step: 0 sleeping 8
id: 2 step: 0 sleeping 2
id: 2 step: 1 sleeping 8
id: 1 step: 1 sleeping 10
id: 2 step: 2 sleeping 2
id: 1 step: 2 sleeping 9
id: 2 step: 3 sleeping 6
id: 1 step: 3 sleeping 1
id: 2 step: 4 sleeping 7
id: 1 step: 4 sleeping 1
id: 2 step: 5 sleeping 5
id: 1 step: 5 sleeping 2
id: 2 step: 6 sleeping 3
id: 1 step: 6 sleeping 10
id: 2 step: 7 sleeping 9
id: 1 step: 7 sleeping 5
id: 2 step: 8 sleeping 2
id: 1 step: 8 sleeping 6
id: 2 step: 9 sleeping 8
id: 1 step: 9 sleeping 7
id: 2 step: 10 sleeping 6
id: 1 step: 10 sleeping 7
id: 2 step: 11 sleeping 9
id: 1 step: 11 sleeping 9
id: 2 step: 12 sleeping 8
id: 1 step: 12 sleeping 8
id: 2 step: 13 sleeping 8
id: 1 step: 13 sleeping 9
id: 2 step: 14 sleeping 1
id: 1 step: 14 sleeping 6
id: 2 step: 15 sleeping 2
id: 1 step: 15 sleeping 9
id: 2 step: 16 sleeping 8
id: 1 step: 16 sleeping 2
id: 2 step: 17 sleeping 10
id: 1 step: 17 sleeping 7
id: 2 step: 18 sleeping 8
id: 1 step: 18 sleeping 2
id: 2 step: 19 sleeping 6
id: 1 step: 19 sleeping 7
id: 2 step: 20 sleeping 4
id: 1 step: 20 sleeping 1
id: 2 step: 21 sleeping 5
id: 1 step: 21 sleeping 4
id: 1 step: 22 sleeping 4
id: 2 step: 22 sleeping 8
id: 1 step: 23 sleeping 9
id: 2 step: 23 sleeping 5
id: 1 step: 24 sleeping 10
id: 2 step: 24 sleeping 4
id: 1 step: 25 sleeping 8
id: 2 step: 25 sleeping 2
id: 1 step: 26 sleeping 10
id: 2 step: 26 sleeping 10
id: 1 step: 27 sleeping 1
id: 2 step: 27 sleeping 6
id: 1 step: 28 sleeping 9
id: 2 step: 28 sleeping 9
id: 1 step: 29 sleeping 4
id: 2 step: 29 sleeping 6
id: 1 step: 30 sleeping 2
id: 2 step: 30 sleeping 1
id: 1 step: 31 sleeping 6
id: 2 step: 31 sleeping 7
id: 1 step: 32 sleeping 7
id: 2 step: 32 sleeping 9
id: 1 step: 33 sleeping 2
id: 2 step: 33 sleeping 3
id: 1 step: 34 sleeping 4
id: 2 step: 34 sleeping 7
id: 1 step: 35 sleeping 4
id: 2 step: 35 sleeping 7
id: 1 step: 36 sleeping 3
id: 2 step: 36 sleeping 9
id: 1 step: 37 sleeping 8
id: 2 step: 37 sleeping 5
id: 1 step: 38 sleeping 8
id: 2 step: 38 sleeping 4
id: 1 step: 39 sleeping 7
id: 2 step: 39 sleeping 1
id: 1 step: 40 sleeping 4
id: 2 step: 40 sleeping 4
id: 1 step: 41 sleeping 8
id: 2 step: 41 sleeping 4
id: 1 step: 42 sleeping 2
id: 2 step: 42 sleeping 10
id: 1 step: 43 sleeping 4
id: 2 step: 43 sleeping 4
id: 1 step: 44 sleeping 2
id: 2 step: 44 sleeping 3
id: 1 step: 45 sleeping 9
id: 2 step: 45 sleeping 7
id: 1 step: 46 sleeping 7
id: 2 step: 46 sleeping 8
id: 1 step: 47 sleeping 1
id: 2 step: 47 sleeping 4
id: 1 step: 48 sleeping 3
id: 2 step: 48 sleeping 4
id: 1 step: 49 sleeping 6
id: 2 step: 49 sleeping 9
id: 1 step: 50 sleeping 6
id: 2 step: 50 sleeping 2
id: 1 step: 51 sleeping 6
id: 2 step: 51 sleeping 8
id: 1 step: 52 sleeping 8
id: 2 step: 52 sleeping 1
id: 1 step: 53 sleeping 1
id: 2 step: 53 sleeping 6
id: 1 step: 54 sleeping 1
id: 2 step: 54 sleeping 3
id: 1 step: 55 sleeping 9
id: 2 step: 55 sleeping 4
id: 1 step: 56 sleeping 2
id: 2 step: 56 sleeping 3
id: 1 step: 57 sleeping 5
id: 2 step: 57 sleeping 8
id: 1 step: 58 sleeping 8
id: 2 step: 58 sleeping 8
id: 1 step: 59 sleeping 2
id: 2 step: 59 sleeping 5
id: 1 step: 60 sleeping 7
id: 2 step: 60 sleeping 3
id: 1 step: 61 sleeping 2
id: 2 step: 61 sleeping 10
id: 1 step: 62 sleeping 7
id: 2 step: 62 sleeping 1
id: 1 step: 63 sleeping 4
id: 2 step: 63 sleeping 7
id: 1 step: 64 sleeping 10
id: 2 step: 64 sleeping 2
id: 1 step: 65 sleeping 3
id: 2 step: 65 sleeping 6
id: 1 step: 66 sleeping 6
id: 2 step: 66 sleeping 1
id: 1 step: 67 sleeping 8
id: 2 step: 67 sleeping 10
id: 1 step: 68 sleeping 9
id: 2 step: 68 sleeping 9
id: 1 step: 69 sleeping 5
id: 1 step: 70 sleeping 4
id: 2 step: 69 sleeping 5
id: 1 step: 71 sleeping 8
id: 2 step: 70 sleeping 3
id: 1 step: 72 sleeping 3
id: 2 step: 71 sleeping 7
id: 1 step: 73 sleeping 10
id: 2 step: 72 sleeping 1
id: 1 step: 74 sleeping 7
id: 2 step: 73 sleeping 2
id: 1 step: 75 sleeping 7
id: 2 step: 74 sleeping 1
id: 1 step: 76 sleeping 2
id: 2 step: 75 sleeping 5
id: 1 step: 77 sleeping 5
id: 2 step: 76 sleeping 6
id: 1 step: 78 sleeping 4
id: 2 step: 77 sleeping 2
id: 1 step: 79 sleeping 1
id: 2 step: 78 sleeping 3
id: 1 step: 80 sleeping 9
id: 2 step: 79 sleeping 8
id: 1 step: 81 sleeping 2
id: 2 step: 80 sleeping 9
id: 1 step: 82 sleeping 5
id: 2 step: 81 sleeping 3
id: 1 step: 83 sleeping 4
id: 2 step: 82 sleeping 3
id: 1 step: 84 sleeping 9
id: 2 step: 83 sleeping 4
id: 1 step: 85 sleeping 9
id: 2 step: 84 sleeping 7
id: 1 step: 86 sleeping 1
id: 2 step: 85 sleeping 6
id: 1 step: 87 sleeping 1
id: 2 step: 86 sleeping 5
id: 1 step: 88 sleeping 3
id: 2 step: 87 sleeping 8
id: 1 step: 89 sleeping 6
id: 2 step: 88 sleeping 2
id: 1 step: 90 sleeping 10
id: 2 step: 89 sleeping 1
id: 1 step: 91 sleeping 4
id: 2 step: 90 sleeping 1
id: 1 step: 92 sleeping 10
id: 2 step: 91 sleeping 1
id: 1 step: 93 sleeping 4
id: 2 step: 92 sleeping 1
id: 1 step: 94 sleeping 5
id: 2 step: 93 sleeping 8
id: 1 step: 95 sleeping 1
id: 2 step: 94 sleeping 6
id: 1 step: 96 sleeping 3
id: 2 step: 95 sleeping 10
id: 1 step: 97 sleeping 1
id: 2 step: 96 sleeping 9
id: 1 step: 98 sleeping 7
id: 2 step: 97 sleeping 6
id: 1 step: 99 sleeping 7
id: 2 step: 98 sleeping 1
id: 2 step: 99 sleeping 7
2
0
1
2
hi 1
hi 3
hi 2
hi 3
hi 2
hi 0
hi 1
hi 0
hi 1
hi 1
hi 3
hi 3
hi 9
hi 0
hi 9
hi 6
hi 4
hi 4
hi 6
hi 0
hi 2
hi 2
[]
[Todd]
[]
[Todd]
[Todd]
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test", "pass flag"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test pass", "flag"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test", "pass", "flag"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test pass flag"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "invalid"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "test", "invalid"}
received args []string{"/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/testargs.36f732ac", "invalid", "pass flag"}
Start
Receive signal interrupt 
End
FAIL
FAIL	github.com/derekparker/delve/proc	23.624s
?   	github.com/derekparker/delve/proc/test	[no test files]
?   	github.com/derekparker/delve/service	[no test files]
?   	github.com/derekparker/delve/service/api	[no test files]
?   	github.com/derekparker/delve/service/debugger	[no test files]
?   	github.com/derekparker/delve/service/rpc1	[no test files]
?   	github.com/derekparker/delve/service/rpc2	[no test files]
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
foo
foo
Hello, World!
foo
Hello, World!
hi
hi
hi
hi
hi
hi
Hello, World!
hi 9
hi 9
hi 5
hi 3
hi 3
hi 7
hi 5
hi 7
hi 1
hi 4
hi 1
hi 6
hi 6
hi 4
hi 8
hi 8
hi 0
hi 2
hi 0
hi 2
--- FAIL: Test1ClientServer_CondBreakpoint (0.39s)
	common_test.go:17: failed assertion at integration1_test.go:967: Continue() - Process 2341 has exited with status 0
Start
Node: root
	Disabled: false
	Redirect IP: 
	Exclude(s):
	Include(s):
----------
Node: hosts
	Disabled: false
	Redirect IP: 192.168.168.1
	Exclude(s):
		rackcdn.com
		schema.org
	Include(s):
		msdn.com
		badgits.org
	Source: hpHosts
		Disabled: false
		Description: 
		Prefix: 127.0.0.0
		URL: http://www.bonzon.com
----------
Node: domains
	Disabled: false
	Redirect IP: 
	Exclude(s):
	Include(s):
----------

&{false 192.168.168.1 [msdn.com badgits.org] [rackcdn.com schema.org] map[hpHosts:0xc820010280]}
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
foo
foo
Hello, World!
foo
Hello, World!
hi
hi
hi
hi
hi
hi
Hello, World!
hi 1
hi 1
hi 5
hi 5
hi 2
hi 2
hi 0
hi 0
hi 3
hi 3
hi 6
hi 6
hi 9
hi 9
hi 4
hi 4
Start
Node: root
	Disabled: false
	Redirect IP: 
	Exclude(s):
	Include(s):
----------
Node: hosts
	Disabled: false
	Redirect IP: 192.168.168.1
	Exclude(s):
		rackcdn.com
		schema.org
	Include(s):
		msdn.com
		badgits.org
	Source: hpHosts
		Disabled: false
		Description: 
		Prefix: 127.0.0.0
		URL: http://www.bonzon.com
----------
Node: domains
	Disabled: false
	Redirect IP: 
	Exclude(s):
	Include(s):
----------

&{false 192.168.168.1 [msdn.com badgits.org] [rackcdn.com schema.org] map[hpHosts:0xc820088000]}
FAIL
FAIL	github.com/derekparker/delve/service/test	33.166s
?   	github.com/derekparker/delve/service/test/cmd	[no test files]

0  0x0000000000000000 in (nil)
   at irrelevant.go:10
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
=>   8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
=>   9:		_ = float64(int(f))
    10:	}
     8:		started <- struct{}{}
     9:		done <- struct{}{}
    10:	}
    11:	
    12:	func stacktraceme() {
=>  13:		return
    14:	}
    15:	
    16:	func main() {
    17:		done := make(chan struct{})
    18:		started := make(chan struct{})
     8:		started <- struct{}{}
     9:		done <- struct{}{}
    10:	}
    11:	
    12:	func stacktraceme() {
=>  13:		return
    14:	}
    15:	
    16:	func main() {
    17:		done := make(chan struct{})
    18:		started := make(chan struct{})
     2:	
     3:	import "runtime"
     4:	
     5:	const N = 10
     6:	
=>   7:	func agoroutine(started chan<- struct{}, done chan<- struct{}, i int) {
     8:		started <- struct{}{}
     9:		done <- struct{}{}
    10:	}
    11:	
    12:	func stacktraceme() {
     2:	
     3:	import "runtime"
     4:	
     5:	const N = 10
     6:	
=>   7:	func agoroutine(started chan<- struct{}, done chan<- struct{}, i int) {
     8:		started <- struct{}{}
     9:		done <- struct{}{}
    10:	}
    11:	
    12:	func stacktraceme() {
SIGQUIT: quit
PC=0x4061beb m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x58000001003, 0x5f4200000f9, 0x1, 0x5f4200000f9, 0x0, 0x49da680, 0x4055229, 0xffffffffffffffff, 0x49da528, 0x7fff5fbff7ec, ...)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sys_darwin_amd64.s:411 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x49da528)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:423 +0xdf
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:439 +0x29
runtime.systemstack(0x7fff5fbff7f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:440 +0x36
runtime.notesleep(0x49daf48)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/lock_sema.go:166 +0xed
runtime.stopm()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820021500, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820209080)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7fff5fbff970)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x47d1588, 0x49ced60, 0xc, 0xc, 0xc820065801)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8203a5f08, 0xc82006dc00)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:515 +0x81
main.main()
	github.com/derekparker/delve/terminal/_test/_testmain.go:76 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 5 [IO wait, 9 minutes]:
net.runtime_pollWait(0x5809ce0, 0x72, 0xc820170001)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200ab720, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200ab720, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200ab6c0, 0xc820170001, 0xdff, 0xdff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820372000, 0xc820170001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82006e1a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82006e1a0, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc82006e1a0, 0x45c8460, 0xc8200af648, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc8200af600, 0xc82037c000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc8204f8120)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:201 +0xd7

goroutine 150 [chan receive, 9 minutes]:
github.com/derekparker/delve/terminal.cont(0xc8202decc0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command.go:565 +0x93
github.com/derekparker/delve/terminal.(*Commands).CallWithContext(0xc8202e2870, 0x46cbe40, 0x8, 0x0, 0x0, 0xc8202decc0, 0x0, 0xffffffffffffffff, 0x0, 0x0, ...)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command.go:252 +0xb3
github.com/derekparker/delve/terminal.(*Commands).Call(0xc8202e2870, 0x46cbe40, 0x8, 0x0, 0x0, 0xc8202decc0, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command.go:257 +0xb3
github.com/derekparker/delve/terminal.(*FakeTerminal).Exec(0xc82055ab80, 0x46cbe40, 0x8, 0x0, 0x0, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command_test.go:44 +0x305
github.com/derekparker/delve/terminal.TestOnPrefix.func1(0xc82055ab80)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command_test.go:320 +0x103
github.com/derekparker/delve/terminal.withTestTerminal(0x472e6c0, 0x12, 0x5808d38, 0xc8201721b0, 0xc8203cff40)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command_test.go:96 +0x586
github.com/derekparker/delve/terminal.TestOnPrefix(0xc8201721b0)
	/Users/gert/go/src/github.com/derekparker/delve/terminal/command_test.go:349 +0x81
testing.tRunner(0xc8201721b0, 0x49cee20)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:582 +0x892

goroutine 151 [chan receive, 9 minutes, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc82026c000)
	/Users/gert/go/src/github.com/derekparker/delve/proc/proc.go:801 +0xc3
created by github.com/derekparker/delve/proc.New
	/Users/gert/go/src/github.com/derekparker/delve/proc/proc.go:78 +0x1d9

goroutine 50 [IO wait, 9 minutes]:
net.runtime_pollWait(0x5809c20, 0x72, 0xc82038c001)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201ba060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201ba060, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201ba000, 0xc82038c001, 0x5ff, 0x5ff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820076018, 0xc82038c001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc820374000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820374000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc820374000, 0x45c8500, 0xc820376020, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc820376000, 0xc8204efa40, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc8204fec80, 0x5f430d8, 0xc820376000, 0x0, 0x0, 0xc8204efa40, 0xc820055e00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc8204fec80, 0x5f430d8, 0xc820376000, 0xc8204fec80, 0xc820378000, 0xc8200aeb80, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc8204fec80, 0x5f430d8, 0xc820376000)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:462 +0x7d
created by github.com/derekparker/delve/service/rpc2.(*ServerImpl).Run.func1
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/server.go:90 +0x1ab

goroutine 98 [IO wait, 9 minutes]:
net.runtime_pollWait(0x5809aa0, 0x72, 0xc82038c601)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200584c0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200584c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820058460, 0xc82038c601, 0x5ff, 0x5ff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8203722c0, 0xc82038c601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc820374340, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820374340, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc820374340, 0x45c8500, 0xc820411a00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc8204119e0, 0xc8200f4540, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc8204d3f00, 0x5f430d8, 0xc8204119e0, 0x0, 0x0, 0xc8200f4540, 0xc8203d3e00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc8204d3f00, 0x5f430d8, 0xc8204119e0, 0xc8204d3f00, 0xc820420640, 0xc8200af900, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc8204d3f00, 0x5f430d8, 0xc8204119e0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:462 +0x7d
created by github.com/derekparker/delve/service/rpc2.(*ServerImpl).Run.func1
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/server.go:90 +0x1ab

goroutine 29 [IO wait, 9 minutes]:
net.runtime_pollWait(0x5809920, 0x72, 0xc82038cc01)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201ba300, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201ba300, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201ba2a0, 0xc82038cc01, 0x5ff, 0x5ff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820372080, 0xc82038cc01, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82006f380, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82006f380, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc82006f380, 0x45c8500, 0xc820550020, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc820550000, 0xc82055adc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc8202bda80, 0x5f430d8, 0xc820550000, 0x0, 0x0, 0xc82055adc0, 0xc820057e00, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc8202bda80, 0x5f430d8, 0xc820550000, 0xc8202bda80, 0xc8202d8010, 0xc820390a80, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc8202bda80, 0x5f430d8, 0xc820550000)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:462 +0x7d
created by github.com/derekparker/delve/service/rpc2.(*ServerImpl).Run.func1
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/server.go:90 +0x1ab

goroutine 82 [IO wait, 9 minutes]:
net.runtime_pollWait(0x5809b60, 0x72, 0xc820562001)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820058450, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820058450, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200583f0, 0xc820562001, 0x3dff, 0x3dff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820076028, 0xc820562001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82006e000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82006e000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc82006e000, 0x45c8460, 0xc820390048, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc820390000, 0xc8204069c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc8203d4000)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:201 +0xd7

goroutine 158 [IO wait, 9 minutes]:
net.runtime_pollWait(0x58099e0, 0x72, 0xc8205ee001)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820348450, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820348450, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203483f0, 0xc8205ee001, 0x1dff, 0x1dff, 0x0, 0x5800028, 0xc820064080)
	/usr/local/Cellar/go/1.6/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820076b20, 0xc8205ee001, 0x1dff, 0x1dff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc8203744e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8203744e0, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc8203744e0, 0x45c8460, 0xc8203915c8, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc820391580, 0xc8202e2930, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc8202dec00)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:201 +0xd7

goroutine 167 [chan receive, 9 minutes]:
net/rpc.(*Client).Call(0xc8202dec00, 0xc8205ff880, 0x11, 0x44c3860, 0xc8205ff860, 0x44b9900, 0xc8203721e8, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/client.go:315 +0xcd
github.com/derekparker/delve/service/rpc2.(*RPCClient).call(0xc82055a900, 0x46b3b90, 0x7, 0x44c3860, 0xc8205ff860, 0x44b9900, 0xc8203721e8, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/client.go:294 +0xb4
github.com/derekparker/delve/service/rpc2.(*RPCClient).Continue.func1(0xc82055a900, 0xc8203768a0)
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/client.go:62 +0x109
created by github.com/derekparker/delve/service/rpc2.(*RPCClient).Continue
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/client.go:91 +0x5d

goroutine 168 [syscall, locked to thread]:
github.com/derekparker/delve/proc._Cfunc_mach_port_wait(0x100005103, 0x0)
	??:0 +0x41
github.com/derekparker/delve/proc.(*Process).waitForStop(0xc82026c000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/proc/proc_darwin.go:336 +0xd1
github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc82026c000, 0xc82039dc70, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/proc/proc_darwin.go:354 +0x42
github.com/derekparker/delve/proc.(*Process).Continue(0xc82026c000, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/proc/proc.go:369 +0x20b
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc8201aea00, 0xc820053a28, 0x0, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/service/debugger/debugger.go:391 +0x848
github.com/derekparker/delve/service/rpc2.(*RPCServer).Command(0xc820409b90, 0xc82043f2d8, 0x8, 0x0, 0x0, 0xc82057f220, 0x0, 0x0)
	/Users/gert/go/src/github.com/derekparker/delve/service/rpc2/server.go:165 +0x3f
reflect.Value.call(0x45a3e80, 0x4698db8, 0x13, 0x46b39d8, 0x4, 0xc820053ee8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45a3e80, 0x4698db8, 0x13, 0xc820053ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc8202bdc40, 0xc8202bda80, 0xc8202d8010, 0xc820390a80, 0xc82055c060, 0x460ad40, 0xc8205ff920, 0x199, 0x44c3f20, 0xc82057f220, ...)
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d

rax    0xe
rbx    0x49dae40
rcx    0x7fff5fbff778
rdx    0x7fff5fbff7f0
rdi    0x1003
rsi    0x5f4200000f9
rbp    0x1003
rsp    0x7fff5fbff778
r8     0x4
r9     0x49c7a80
r10    0xc820021ac0
r11    0x286
r12    0x771e812d234
r13    0xdeffd9ed248
r14    0x14504286305f1600
r15    0x36
rip    0x4061beb
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/derekparker/delve/terminal	600.012s
?   	github.com/derekparker/delve/version	[no test files]
make: *** [test] Error 1
```
